# Generated by Django 4.2.5 on 2023-10-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auctions',
            new_name='Auction',
        ),
    ]
