# Generated by Django 4.2.5 on 2023-10-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_rename_auctions_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='auction\\static\\sneaker1.jpg'),
        ),
    ]
