# Generated by Django 4.2.5 on 2023-10-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_auction_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='image_url',
            new_name='image',
        ),
    ]
