# Generated by Django 4.2.5 on 2023-10-10 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_alter_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 7, 17, 48, 107227, tzinfo=datetime.timezone.utc)),
        ),
    ]
