# Generated by Django 4.2.5 on 2023-10-10 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auction_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
