# Generated by Django 4.2.5 on 2023-10-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_alter_auction_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='time_remained',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
