# Generated by Django 4.2.5 on 2023-10-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_alter_auction_time_remained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='time_remained',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
