# Generated by Django 4.2.5 on 2023-10-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_alter_auction_time_remained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='time_remained',
        ),
        migrations.AddField(
            model_name='auction',
            name='seconds_remained',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
