# Generated by Django 4.2.5 on 2023-10-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_remove_auction_time_remained_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='seconds_remained',
        ),
    ]
